import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    position: "relative",
    backgroundColor: "#fff",
    width: "100%",
    height: "100%",
    display: "flex",
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,

    marginTop: "auto",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 44,
    paddingHorizontal: 10,
    paddingVertical: 11,
    marginBottom: 32,
    borderBottomWidth: 2,
    borderBottomColor: "#E8E8E8",

    // borderWidth: 1,
    // borderColor: "#000",
  },
  headerTitle: {
    flexGrow: 2,
    color: "#212121",
    textAlign: "center",
    fontFamily: "Roboto-Medium",
    fontSize: 17,
  },
  content: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: "auto",
    paddingHorizontal: 16,
  },
  avatarImg: {
    width: 60,
    height: 60,
    borderRadius: 16,
    marginRight: 8,
  },
  userName: {
    color: "#212121",
    fontFamily: "Roboto-Bold",
    fontSize: 13,
  },
  userEmail: {
    color: "#212121CC",
    fontFamily: "Roboto-Regular",
    fontSize: 11,
  },
  bottomTabs: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    width: "100%",
    height: 58,
    paddingHorizontal: 9,
    gridGap: 16,
    marginTop: 100,
    borderTopWidth: 2,
    borderTopColor: "#E8E8E8",
  },
  btnBottomTabs: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    height: 40,
    borderRadius: 100,
    backgroundColor: "#F6F6F6",
  },
});

export default styles;
